---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_CLAIM:-${APP}}
  namespace: ${NAMESPACE:-default}
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-iscsi"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_CAPACITY:-1Gi}
  storageClassName: truenas-ssd-iscsi
