---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: &app dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.22.1
  replicas: 3
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    # BullMQ extensively uses Lua scripts (server-side scripting) for executing
    # commands in Redis. Immich needs this to be set.
    # Ref:
    #   - https://www.dragonflydb.io/docs/integrations/bullmq#using-undeclared-keys-not-optimized
    #   - https://immich.app/docs/developer/architecture#redis
    - --default_lua_flags=allow-undeclared-keys
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: *app
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
