---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name prowlarr-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        APIKEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
    - extract:
        key: prowlarr
