---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app navitest
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: democratic-csi-iscsi
    - name: external-secrets-stores
    - name: volsync
  path: ./kubernetes/apps/media/navitest/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      APP_UID: &uid "5000"
      APP_GID: *uid
      VOLSYNC_CLAIM: navitest-data
      VOLSYNC_ACCESSMODES: &accessModes ReadWriteOnce
      VOLSYNC_STORAGECLASS: &storageClass truenas-ssd-iscsi
      VOLSYNC_SNAPSHOTCLASS: *storageClass
      VOLSYNC_CACHE_ACCESSMODES: *accessModes
      VOLSYNC_CACHE_SNAPSHOTCLASS: *storageClass
      VOLSYNC_CAPACITY: &capacity 2Gi
      VOLSYNC_CACHE_CAPACITY: *capacity
      VOLSYNC_TIME: 08 12 * * *
