---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster16.yaml
  - ./cluster16-immich.yaml
  - ./gatus.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./service.yaml
