---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: democratic-csi-iscsi
    - name: external-secrets-stores
    - name: volsync
  path: ./kubernetes/apps/database/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      APP_UID: &uid "5050"
      APP_GID: *uid
      VOLSYNC_CLAIM: pgadmin-data
      VOLSYNC_ACCESSMODES: &accessModes ReadWriteOnce
      VOLSYNC_STORAGECLASS: &storageClass truenas-ssd-iscsi
      VOLSYNC_SNAPSHOTCLASS: *storageClass
      VOLSYNC_CACHE_ACCESSMODES: *accessModes
      VOLSYNC_CACHE_SNAPSHOTCLASS: *storageClass
      VOLSYNC_CAPACITY: &capacity 1Gi
      VOLSYNC_CACHE_CAPACITY: *capacity
      VOLSYNC_TIME: "0 3 * * *"
