---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name unpackerr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        UN_RADARR_0_API_KEY: "{{ .RADARR_API_KEY }}"
        UN_SONARR_0_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
