---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30h
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 65.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: prometheus-operator-crds
      namespace: observability
    - name: democratic-csi-iscsi
      namespace: storage
  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics.yaml
  values:
    crds:
      enabled: false
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - &host alertmanager.${SECRET_DOMAIN}
        pathType: Prefix
        tls:
          - hosts:
              - *host
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: alertmanager
        storage:
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: truenas-ssd-iscsi
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: false
      forceDeployDashboards: true
      defaultDashboardsTimezone: browser
      sidecar:
        dashboards:
          annotations:
            grafana_folder: Kubernetes
    kubeApiServer:
      serviceMonitor:
        selector:
          k8s-app: kube-apiserver
    kubeControllerManager: &kubeControllerManager
      service:
        selector:
          k8s-app: kube-controller-manager
    kubeEtcd:
      <<: *kubeControllerManager # etcd runs on control plane nodes.
    kubeScheduler:
      service:
        selector:
          k8s-app: kube-scheduler
    kubeProxy:
      enabled: false # Replced with Cilium.
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      metricLabelsAllowlist:
        - pods=[*]
        - deployments=[*]
        - persistentvolumeclaims=[*]
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
            - action: replace
              regex: (.*)
              replacement: $1.${SECRET_DOMAIN}:9100
              sourceLabels:
                - kubernetes_node
              targetLabel: instance
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - &host prometheus.${SECRET_DOMAIN}
        pathType: Prefix
        tls:
          - hosts:
              - *host
      prometheusSpec:
        scrapeInterval: 30s # Must match interval in Grafana Helm chart.
        enableAdminAPI: true
        enableFeatures:
          - auto-gomemlimit
          # https://prometheus.io/docs/prometheus/latest/feature_flags/
          - memory-snapshot-on-shutdown
          - new-service-discovery-manager
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        retention: 14d
        retentionSize: 90GB
        walCompression: true
        resources:
          requests:
            cpu: 300m
          limits:
            memory: 1500Mi
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              storageClassName: truenas-ssd-iscsi
              resources:
                requests:
                  storage: 100Gi
