---
# Areas
- { name: "area/docs",                  color: "0e8a16", description: "Changes made in the docs directory"       }
- { name: "area/github",                color: "0e8a16", description: "Changes made in the github directory"     }
- { name: "area/kubernetes",            color: "0e8a16", description: "Changes made in the kubernetes directory" }
- { name: "area/talos",                 color: "0e8a16", description: "Changes made in the talos directory"      }
- { name: "area/taskfiles",             color: "0e8a16", description: "Changes made in the taskfiles directory"  }
# Renovate
- { name: "renovate/container",         color: "027fa0" }
- { name: "renovate/github-action",     color: "027fa0" }
- { name: "renovate/github-release",    color: "027fa0" }
- { name: "renovate/grafana-dashboard", color: "027fa0" }
- { name: "renovate/helm",              color: "027fa0" }
# Semantic Type
- { name: "type/digest",                color: "ffec19" }
- { name: "type/patch",                 color: "ffec19" }
- { name: "type/minor",                 color: "ff9800" }
- { name: "type/major",                 color: "f6412d" }
# Uncategorized
- { name: "hold",                       color: "ee0701" }
