---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name home-selfsigned-ca
spec:
  isCA: true
  commonName: *name
  subject:
    organizations:
      - ${SECRET_DOMAIN}
  secretName: *name
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name strong-selfsigned-ca
spec:
  isCA: true
  commonName: *name
  subject:
    organizations:
      - ${SECRET_DOMAIN}
  secretName: *name
  privateKey:
    algorithm: ECDSA
    size: 384
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
