---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./priorityclass.yaml
  # Flux-Kustomizations
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./jellystat/ks.yaml
  - ./lidarr/ks.yaml
  - ./navidrome/ks.yaml
  # - ./navitest/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./unpackerr/ks.yaml
