---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TALOS_DIR: "{{.ROOT_DIR}}/talos"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubernetes/kubeconfig"
  TALOSCONFIG: "{{.ROOT_DIR}}/talos/clusterconfig/talosconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  flux: .taskfiles/flux
  sops: .taskfiles/sops
  talos: .taskfiles/talos
  workstation: .taskfiles/workstation

tasks:

  default: task --list
