---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM:-${APP}}
  namespace: ${NAMESPACE:-default}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${APP}-rdst
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:-1Gi}
  storageClassName: ${VOLSYNC_STORAGECLASS:-truenas-ssd-iscsi}
