---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name portainer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: portainer
