---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app portainer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: democratic-csi-iscsi
      namespace: storage
  values:
    controllers:
      portainer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          portainer:
            image:
              repository: docker.io/portainer/portainer-ce
              tag: 2.21.0-alpine@sha256:a3dd960478f95352fa2e3a52d64787bd0fa656a66fff4eb87bbdf89e27fae7d2
            args:
              - --admin-password-file
              - /tmp/admin
            env:
              TZ: ${TIMEZONE}
              ANONYMOUS_USAGE: 0
            envFrom:
              - secretRef:
                  name: portainer-secret
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    serviceAccount:
      create: true
      name: *app
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: &host portainer-k8s.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      admin:
        enabled: true
        type: secret
        name: portainer-secret
        globalMounts:
          - path: /tmp/admin
            subPath: ADMIN_PASSWORD
            readOnly: true
      data:
        existingClaim: portainer-data
        globalMounts:
          - path: /data
