---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dcgm-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: dcgm-exporter
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: dcgm-exporter
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: nvidia-device-plugin
      namespace: kube-system
  values:
    image:
      repository: nvcr.io/nvidia/k8s/dcgm-exporter
      tag: 3.1.7-3.1.4-ubuntu20.04
    extraEnv:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    resources:
      limits:
        nvidia.com/gpu: 1
    nodeSelector:
      nvidia.com/gpu.present: "true"
    runtimeClassName: nvidia
    serviceMonitor:
      enabled: true
      interval: 15s
      honorLabels: true
