---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudflared-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_TUNNEL_ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID }}"
          }
  dataFrom:
    - extract:
        key: cloudflare
