---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./flaresolverr/ks.yaml
  - ./pinchflat/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./recyclarr/ks.yaml
