---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app recyclarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: democratic-csi-nfs
      namespace: storage
  values:
    controllers:
      recyclarr:
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          timeZone: &tz ${CONFIG_TIMEZONE}
          schedule: "@daily"
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          recyclarr:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 7.3.0@sha256:2aaa0205a93171b93a159e4665004ccee1a5aacd60359fb8d7683db0ae7e774b
            env:
              TZ: *tz
            envFrom:
              - secretRef:
                  name: *app
            args: ["sync"]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 5000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
      config-file:
        type: configMap
        name: recyclarr-config
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
