---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: recyclarr-config-file
    files:
      - recyclarr.yml=./resources/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
