---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DB_DATABASE_NAME: immich
        DB_HOSTNAME: pgvectors-rw.database.svc.cluster.local
        DB_USERNAME: "{{ .IMMICH_POSTGRES_USER }}"
        DB_PASSWORD: "{{ .IMMICH_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: immich
