---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: immich-config
    files:
      - immich.json=./resources/immich-config.json
generatorOptions:
  disableNameSuffixHash: true
