---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: truenas-ssd-iscsi
  resources:
    requests:
      storage: 10Gi
