---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: flux-system
spec:
  targetNamespace: self-hosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: democratic-csi-iscsi
    - name: dragonfly-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/self-hosted/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      PVC_ACCESSMODES: ReadWriteOnce
      PVC_STORAGECLASS: ${CLUSTER_STORAGE_BLOCK}
      PVC_CAPACITY: 10Gi
