---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./dokuwiki/ks.yaml
  - ./it-tools/ks.yaml
  - ./portainer/ks.yaml
