---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app silence-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    configMaps:
      config:
        enabled: true
        data:
          config.yml: |
            server:
              enable:
                debug:
                  server: true
              listen:
                address: 'http://0.0.0.0:8000'
            service:
              alertmanager:
                address: http://alertmanager-operated.observability.svc.cluster.local:9093
              kubernetes:
                address: ''
                inCluster: true
                tls:
                  caFile: ''
                  crtFile: ''
                  keyFile: ''
    controllers:
      silence-operator:
        containers:
          silence-operator:
            image:
              repository: quay.io/giantswarm/silence-operator
              tag: 0.11.2
            args:
              - daemon
              - --config.dirs=/var/run/silence-operator/configmap/
              - --config.files=config
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8000
                  initialDelaySeconds: 15
                  periodSeconds: 20
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 1000
        runAsGroup: *uid
        seccompProfile: { type: RuntimeDefault }
    serviceAccount:
      create: true
      name: silence-operator
    persistence:
      config:
        enabled: true
        type: configMap
        identifier: config
        globalMounts:
          - path: /var/run/silence-operator/configmap
