---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name democratic-csi-nfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          httpConnection:
            protocol: https
            host: nas.${SECRET_DOMAIN}
            port: 443
            apiKey: {{ .TRUENAS_API_KEY }}
            allowInsecure: false
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}`}}/{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: ssd-data/K8s/NFS/Vols
            detachedSnapshotsDatasetParentName: ssd-data/K8s/NFS/Snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0770"
            datasetPermissionsUser: 5000
            datasetPermissionsGroup: 5000
          nfs:
            shareCommentTemplate: "{{`{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}`}}-{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            shareHost: {{ .TRUENAS_IP }}
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: [10.0.100.0/24]
            shareMaprootUser: ""
            shareMaprootGroup: ""
            shareMapallUser: k8s
            shareMapallGroup: appdata
  dataFrom:
    - extract:
        key: truenas
