---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: v0.0.25
      sourceRef:
        kind: HelmRepository
        name: spegel
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: spegel-helm-values
  values:
    grafanaDashboard:
      enabled: false
    serviceMonitor:
      enabled: true
    # TODO: Remove after spegel is stable on Talos v1.8
    # https://github.com/spegel-org/spegel/releases
    # For more information, see https://github.com/spegel-org/spegel/issues/579
    image:
      repository: ghcr.io/deedee-ops/spegel
      tag: 0.0.24
      digest: ""
