---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lidarr-exporter-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        APIKEY: "{{ .LIDARR_API_KEY }}"
  dataFrom:
    - extract:
        key: lidarr
