---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./exporters
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./promtail/ks.yaml
  - ./silence-operator/ks.yaml
  - ./unpoller/ks.yaml
