apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:W8huZQKqE0DoIoHR,iv:w/N7wvz+V4YVKRrVdnb1HUNkJtN9EA5nwIC0lv+rvP0=,tag:B5uji42fxTmrdvmufCY4eQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:PcpL6OY8XS5fUxTgEw==,iv:uryoRBLK0PQttw4YFp31nDOsrZ0EN8eHBv4N+23BF2Q=,tag:HEqCDlXYDqpcHCgf7L1gBw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:a3ZRTNKFK4TZU0WvAUpVOXuvrjqXJ90jGAHOCwzvoks2MSQg,iv:ZQQP6jroRJ1XHqWj8Ff8iPY4nlZ4fzxIZJ/XRe7PXe4=,tag:mGFYEVMI4mIb3NRuS7+Lkg==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:L1k2Ks+qhLQ7qQ==,iv:qFscF2ijUmO5n6Mzrta/0PmE0I7PxyFOMgWuquM/jHA=,tag:rr+11ds1MjbRqeZxitqqEA==,type:str]
    TRUENAS_API_KEY_K8S: ENC[AES256_GCM,data:Q8V8o7jomV9pa04yPzUdLzyOv2zQKi4RFOR3vfyC98Qy3FYHSBAD5WQWEmyfpvfLQw1EiFaIqPVd19Z0aYbPRITF,iv:EiX1BBZisWjT0Y5te0fwtVjp4p25ZRoieXH4o9kJQ4I=,tag:Qo9X+g9F/f4Ql+OAU2u8Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM3RKRk5CVG1KSjhhSlI4
            RWJXNFJvUkZQOS8xdFpoMHpsaUI3SWIveUh3ClhYK2ZFT3RZczA3OWV6TWZqZ1Ja
            eXBvT241cXkwNXB2dmJaeUU1cUE4NGMKLS0tIHpMOHYweUhROU9STlJnRk92RE1C
            bXNGR1lYSXlHcGNoQUJlVlA3a1lwZVUKWmea3A7EkvOeWwiIlmgMDs5ICReeO3Il
            aFJZuTNxUrD1XFIjBdMNljrESt2/o87gwW3oQYJZ09prp0PyE1AQhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T20:32:42Z"
    mac: ENC[AES256_GCM,data:VxtHCGn4NspF+hkyWvh22vwwb3wB7LIVUxe54L7NJmRlRYBBMInYHkZ5Ybh5f2Qh/N2VDV0coZYdE/c8FXNEYab3VKo2OgUYxJ2FUfJitjvYKFoM0xEoCRKPxVMZ4pfQMR/nMLrtxBn3NlRcYociRtQ2DzbZJCW+eKtNJG+WbKw=,iv:G+ifT7mMDYtG85jxiKbNNA5X7ru2zYGMrR/VHVji030=,tag:j93LZcNZLXVLsaS83rKZEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
