---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redisinsight
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: democratic-csi-iscsi
      namespace: storage
  values:
    controllers:
      redisinsight:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          redisinsight:
            image:
              repository: redis/redisinsight
              tag: 2.58.0@sha256:c3885a6b0fe11b7f33001c0586af0a82101f9a4ab83d5af55f1904f5fc642815
            env:
              TZ: ${CONFIG_TIMEZONE}
              RI_FILES_LOGGER: false
              RI_STDOUT_LOGGER: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 5000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        # Service name should not be 'redisinsight' since the service creates
        # environment variables that conflicts with redisinsight application's
        # environment variables: REDISINSIGHT_HOST and REDISINSIGHT_PORT
        nameOverride: svc
        controller: *app
        ports:
          http:
            port: 5540
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
