apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bitwarden-access-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:LyHhEFC00WfiBAxesTEjW43ot52DQyD+637MxkWerniYPAEhy7aIgUg19o5xj5h4Q9AvCjcg3ydvOdYh5prUtfiSFCTQ02sRGK36yDiPt/IyiBjohG1WIjJTOU/mEA==,iv:j2CnOVQWCYg+7PWYYZ4beAvA6rOGBPEOJnpzVDHWu6g=,tag:TUyKS1z7GK0tpUKyH4mjMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDVUQWd0L3JYcVk3MG84
            aHd5NHAzN3VIdnVsVmtTNTFoMjIwRGdKSlRNCld6d2J6VzJuc24xMGUxQUtsRzNq
            REI3Vk1iYW9uNkQwN3MvYmlqNVhGanMKLS0tIGhqNTVGN1cybFJzekFvemtaL0Ew
            ZXhVdE5EN3NpY1JTTHRUK0NSNjRrREkK9Komtl2N9THlQC+mWJLUWjLlojYlY0Je
            yQlvcAJScvOP1swNBxkZua8xFE6PHln8Y2YfpvNbIZ+3K9im2bWKaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T20:39:28Z"
    mac: ENC[AES256_GCM,data:1pJdaeREjGYL100W/QhfnCVLo0dlKNztQdUR2s+QPFVITMzweKnRaq9CiKZ/CXTuTQVMyNZDIPw5lhHpzUQTC1Ki9xfjSaT3a3nBom0eKk50tLVYs6T5JcbSOG/kBFOWvPOZ+KFpgusud0oHgGN1GTK+tPwWHhKg1hNoNy+KtYk=,iv:7ZfIHbzSapZW+Udu3PS9iFDDvX4bZtdN5kCGz5DGGKQ=,tag:fJYUdalsoio7UtIJfyuDSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
