---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: security
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        key: ca.crt
      organizationID: ${BW_ORG_ID}
      projectID: ${BW_PROJECT_ID}
