{
 "title": "Prometheus Blackbox Exporter",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "target", "query": { "query": "query_result(probe_success)" } },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Global Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(instance) (probe_icmp_duration_seconds{phase=\"rtt\",instance=~\"$target\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "target",
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_success{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\",instance=~\"$target\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_icmp_duration_seconds{phase=\"rtt\",instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  }
 ]
}