{
 "title": "Exportarr",
 "tags": [
  "sonarr",
  "radarr",
  "lidarr",
  "prowlarr",
  "music",
  "movies",
  "tv",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "prowlarr_instance",
    "label": "Prowlarr Instance",
    "query": {
     "query": "label_values({__name__=~\"prowlarr_.*\"},instance)"
    }
   },
   {
    "name": "radarr_instance",
    "label": "Radarr Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},instance)"
    }
   },
   {
    "name": "radarr_path",
    "label": "Radarr Root Folder",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"},path)"
    }
   },
   {
    "name": "sonarr_instance",
    "label": "Sonarr Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},instance)"
    }
   },
   {
    "name": "sonarr_path",
    "label": "Sonarr Root Folder",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"},path)"
    }
   },
   {
    "name": "lidarr_instance",
    "label": "Lidarr Instance",
    "query": {
     "query": "label_values({__name__=~\"lidarr_.*\"},instance)"
    }
   },
   {
    "name": "lidarr_path",
    "label": "Lidarr Root Folder",
    "query": {
     "query": "label_values({__name__=~\"lidarr_.*\"},path)"
    }
   },
   {
    "name": "bazarr_instance",
    "label": "Bazarr Instance",
    "query": {
     "query": "label_values({__name__=~\"bazarr_.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prowlarr - ${prowlarr_instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "prowlarr_instance"
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prowlarr_system_status{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total{instance=~\"${prowlarr_instance}\"} - prowlarr_indexer_enabled_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) / sum(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"})",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms{instance=~\"${prowlarr_instance}\"}) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__rate_interval])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "prowlarr_system_health_issues{instance=~\"${prowlarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total{instance=~\"${prowlarr_instance}\"}[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bazarr - ${bazarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "bazarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_system_status{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"bazarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "bazarr_subtitles_missing_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "bazarr_subtitles_monitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "bazarr_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "bazarr_subtitles_wanted_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Episode Subtitles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_episode_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "bazarr_episode_subtitles_missing_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "bazarr_episode_subtitles_monitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "bazarr_episode_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "bazarr_episode_subtitles_wanted_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Movie Subtitles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bazarr_movie_subtitles_downloaded_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "bazarr_movie_subtitles_missing_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "bazarr_movie_subtitles_monitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "bazarr_movie_subtitles_unmonitored_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "bazarr_movie_subtitles_wanted_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Providers",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "bazarr_subtitles_provider_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bazarr_subtitles_score_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "{{score}}"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bazarr_subtitles_language_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "{{language}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"bazarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"bazarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "bazarr_episode_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Episoded"
    },
    {
     "expr": "bazarr_movie_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Movies"
    },
    {
     "expr": "bazarr_subtitles_filesize_total{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "bazarr_system_health_issues{instance=~\"${bazarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lidarr - ${lidarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "lidarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_system_status{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"lidarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_artists_filesize_bytes{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_history_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "lidarr_songs_downloaded_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Songs"
    }
   ]
  },
  {
   "title": "Songs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_songs_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Artists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_artists_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "lidarr_artists_monitored_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Monitored"
    }
   ]
  },
  {
   "title": "Albums",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lidarr_albums_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "lidarr_albums_missing_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "lidarr_albums_monitored_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Monitored"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "lidarr_songs_quality_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Artist Genres",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 53 },
   "targets": [
    {
     "expr": "lidarr_artists_genres_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "{{genre}}"
    }
   ]
  },
  {
   "title": "Album Genres",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 53 },
   "targets": [
    {
     "expr": "lidarr_albums_genres_total{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "{{genre}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"lidarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"lidarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "lidarr_artists_filesize_bytes{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum by (path) (lidarr_rootfolder_freespace_bytes{instance=~\"${lidarr_instance}\",path=~\"${lidarr_path}\"})",
     "legendFormat": "Disk Free: {{path}}"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "lidarr_system_health_issues{instance=~\"${lidarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Radarr - ${radarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 }, "repeat": "radarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_system_status{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_history_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "radarr_movie_downloaded_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Movies"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "radarr_movie_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "radarr_movie_missing_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "radarr_movie_monitored_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_unmonitored_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Unmonitored"
    },
    {
     "expr": "radarr_movie_wanted_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Wanted"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "radarr_movie_quality_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{instance=~\"${radarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum by (path) (radarr_rootfolder_freespace_bytes{instance=~\"${radarr_instance}\",path=~\"${radarr_path}\"})",
     "legendFormat": "Disk Free: {{path}}"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 88 },
   "targets": [
    {
     "expr": "radarr_system_health_issues{instance=~\"${radarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sonarr - ${sonarr_instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 }, "repeat": "sonarr_instance" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_system_status{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_history_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sonarr_episode_downloaded_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Episodes"
    },
    {
     "expr": "sonarr_season_downloaded_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Seasons"
    },
    {
     "expr": "sonarr_series_downloaded_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sonarr_episode_missing_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "sonarr_episode_monitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sonarr_episode_unmonitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Unmonitored"
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_season_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sonarr_season_monitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sonarr_season_unmonitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Unmonitored"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarr_series_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sonarr_series_monitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sonarr_series_unmonitored_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Unmonitored"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sonarr_episode_quality_total{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "{{quality}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum by (path) (sonarr_rootfolder_freespace_bytes{instance=~\"${sonarr_instance}\",path=~\"${sonarr_path}\"})",
     "legendFormat": "Disk Free: {{path}}"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 117 },
   "targets": [
    {
     "expr": "sonarr_system_health_issues{instance=~\"${sonarr_instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}