---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns-cloudflare-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        CF_API_EMAIL: "{{ .CLOUDFLARE_EMAIL }}"
        CF_API_KEY: "{{ .CLOUDFLARE_API_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare
