---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Meta: Sync labels"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          token: "${{ steps.app-token.outputs.token }}"
          delete-other-labels: true
