---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name ${APP}-volsync-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:https://s3.${SECRET_DOMAIN}/volsync/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_ROOT_USER }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync
    - extract:
        key: minio
