---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}-rsrc
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "${VOLSYNC_TIME:-0 0 * * *}"
  restic:
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    copyMethod: Snapshot
    storageClassName: "${VOLSYNC_STORAGECLASS:-truenas-ssd-iscsi}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-truenas-ssd-iscsi}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-truenas-ssd-iscsi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    pruneIntervalDays: 7
    repository: ${APP}-volsync-secret
    retain:
      daily: 7
      within: 3d
    moverSecurityContext:
      runAsUser: ${APP_UID:-5000}
      runAsGroup: ${APP_GID:-5000}
      fsGroup: ${APP_GID:-5000}




