---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${APP}-rdst
spec:
  trigger:
    manual: restore-once
  restic:
    accessModes: ["${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    copyMethod: Snapshot
    storageClassName: "${VOLSYNC_STORAGECLASS:-truenas-ssd-iscsi}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-truenas-ssd-iscsi}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-1Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-truenas-ssd-iscsi}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    repository: ${APP}-volsync-secret
    moverSecurityContext:
      runAsUser: ${APP_UID:-5000}
      runAsGroup: ${APP_GID:-5000}
      fsGroup: ${APP_GID:-5000}



